### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by zer0cat** [capt-meelo/NtCreateUserProcess#1]
Hello!
CreateProcess don't work, write "invalid parameter". Can you give me .exe  for debug?? Windows 10 x64

**Comment by capt-meelo** [comment]
What process are you trying to spawn?

**Comment by zer0cat** [comment]
I don't change your sample
so, calc.exe

**Comment by capt-meelo** [comment]
I just tested it (again) in both Win10 and Win11 and it's working.

**Comment by zer0cat** [comment]
Can you give me a build (exe file) ??

**Comment by capt-meelo** [comment]
Unfortunately, no.

**Comment by zer0cat** [comment]
Sorry author! All works! In 64 bit system programs also must be 64 bit! But I tried 32, that fails!

delete please this stupid.

**Comment by capt-meelo** [comment]
No worries about it.
