### ISSUE TITLE
Code doesn't seem to work for executables outside of `System32`

### ISSUE THREAD

**Issue by Barracuda72** [capt-meelo/NtCreateUserProcess#2]
First I'd like to thank you for your great article! It was really interesting and inspiring to read and follow.

Next, I'd like to report kind of an interesting behaviour, maybe helpful for anyone who comes with a same problem. 

I've tried to launch different programs and noticed that it's impossible to start any EXE from outside `System32` folder. E.g. you can't launch `\\??\\C:\\Windows\\notepad.exe`, `NtCreateUserProcess` returns `STATUS_OBJECT_PATH_INVALID`. Interestingly, on Wine the same executable works and launches notepad successfully, so I think it has to do something with very deep NT internal stuff.

**Comment by capt-meelo** [comment]
It has something to do with CSRSS. Another researcher made a post about it. You can read more about it here: https://www.coresecurity.com/core-labs/articles/creating-processes-using-system-calls

**Comment by Barracuda72** [comment]
Oh, thank you for pointing this out!
