### ISSUE TITLE
Avoid new window

### ISSUE THREAD

**Issue by massimiliano-dalcero** [capt-meelo/NtCreateUserProcess#4]
hello,
sorry if I open an issue for discussion.

I am studying NtCreateUserProcess for practice, work and personal study.Thanks to your contribution I was able to understand a few things and I thank you for your article and code.

After banging my head for two days, however, I was unable to do one thing:
I would like to start a terminal application within the same console but instead it always opens a new window.
An example to try is if I run "powershell", I would like it to run in the same context as the execution console.

With your experience, do you have something in mind where I could look?

**Comment by capt-meelo** [comment]
Instead of `main`, use `WinMain` like:

```
int WinMain(HINSTANCE hInstance,
            HINSTANCE hPrevInstance, 
            LPTSTR    lpCmdLine, 
            int       cmdShow)
{
    /* code here */
}
```

Then make sure to set the option Linker->System->SubSystem to `Windows (/SUBSYSTEM:WINDOWS)` instead of `Console (/SUBSYSTEM:CONSOLE`

**Comment by massimiliano-dalcero** [comment]
hello @capt-meelo 
I will try in this week 🙏
thanks for your kindness response 😊
